version: "1.0"
info:
  model: int-scaffold
packages:
- name: TestProject2Project
  gitServerName: rlakshitha0912
  gitUrl: https://github.com/rlakshitha0912/TestProject2Project
  gitUsername: rlakshitha0912
  gitBranch: main
- name: TestAdapaterPackage
  gitServerName: rlakshitha0912
  gitUrl: https://github.com/rlakshitha0912
  gitUsername: rlakshitha0912
  gitBranch: main
